# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: RC_Agent
  demands: maven

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '17'
    addToPath: true
    setAsDefault: true

- task: Maven@4
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'
    jdkVersionOption: 1.17

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/resources'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/resources'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/resources'
    ArtifactName: 'drop'
    publishLocation: 'Container'
